### ISSUE TITLE
Update dependencies for v0.1.0

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-contravariant#2]
- [x] purescript-const
- [x] purescript-bifunctors
- [ ] purescript-lens
- [ ] purescript-argonaut

**Comment by paf31** [comment]
This breaks the CI build for `purescript` right now (or rather, it doesn't build anything because Bower bails out), just fyi.

**Comment by garyb** [comment]
Whoops, sorry. I hadn't jumped-to on this due to the potential pending name change, #3. Thoughts on that?

**Comment by paf31** [comment]
Honestly, I don't think it's worth the hassle. I think `Contravariant` is a fine name.
