### ISSUE TITLE
New release for 0.13.0?

### ISSUE THREAD

**Issue by danieljharvey** [purescript/purescript-contravariant#22]
Hello!

The new version of the compiler is having a bad time with the self import that has been fixed in #21 - would it be possible to do a new release with this fix in?

Thanks!
Dan

**Comment by garyb** [comment]
This was [fixed and released while ago](https://github.com/purescript/purescript-contravariant/releases/tag/v4.0.1), if you're using a package set, perhaps you need to update that to a newer one? 🙂
