### ISSUE TITLE
No instance found for Prelude.Semigroup (a6536 -> a6536 -> Prelude.Ordering)

### ISSUE THREAD

**Issue by alexbiehl** [purescript/purescript-contravariant#4]
Hi, 

I am using purescript-contravariant with psc version 0.6.8 and it gives me: 

```
Error at bower_components/purescript-contravariant/src/Data/Comparison.purs line 16, column 1 - line 19, column 1:
Error in declaration semigroupComparison
No instance found for Prelude.Semigroup (a6536 -> a6536 -> Prelude.Ordering)
```

**Comment by garyb** [comment]
Ah, the `Semigroup` instance for `Ordering` was added to the `Prelude` in psc 0.6.9.

**Comment by alexbiehl** [comment]
Oh dang, must have miss that! Thank you!

**Comment by garyb** [comment]
I think we missed it from the psc release notes actually, I'll update them now.
